;;; Malabar mode setup, requires: cedet and semantic
;;; @see https://github.com/m0smith/malabar-mode

;;;
;;; Attempt to copy install bunubot
;;;
;; (require 'cedet)
;; (require 'semantic)
;; (load "semantic/loaddefs.el")
;; (semantic-mode 1)

                                        ;(add-to-list 'load-path "~/.emacs.d/site-lisp/malabar/current/lisp")
;; (require 'malabar-mode)

;; (add-to-list 'auto-mode-alist '("\\.java\\'" . malabar-mode))

;;;
;;; Attempting to manually install 1.x
;;;
;; ;;(add-to-list 'load-path "~/.emacs.d/site-lisp/malabar/malabar-1.4.0/lisp")
;; (require 'cedet)
;; (require 'semantic)
;; (load "semantic/loaddefs.el")
;; (semantic-mode 1)

;; (add-to-list 'load-path "~/.emacs.d/site-lisp/malabar/current/lisp")
;; (require 'malabar-mode)

;; ;;(setq malabar-groovy-lib-dir "~/.emacs.d/site-lisp/malabar/malabar-1.4.0/lib")
;; ;(setq malabar-groovy-lib-dir "~/.emacs.d/site-lisp/malabar/current/lib")

;; (add-to-list 'auto-mode-alist '("\\.java\\'" . malabar-mode))


;;;
;;; Attempting to install 2.x
;;;

;; Manually installed groovy-mode from melpa, version 20141209.1133,
;; the automatic install via 'require-package would only install the
;; old version from melpa-stable
;;(require-package 'groovy-mode)
;; (require-package 'malabar-mode)


                                        ;
;; (add-hook 'after-init-hook (lambda ()
;;                              (message "activate-malabar-mode")
;;                              (activate-malabar-mode)))
;; (add-hook 'malabar-java-mode-hook 'flycheck-mode)
;; (add-hook 'malabar-groovy-mode-hook 'flycheck-mode)

;; (add-hook 'malabar-mode-hook
;;           (lambda ()
;;             (add-hook 'after-save-hook
;;                       'malabar-compile-file-silently nil t)))

;; Use `jtags-extras-organize-imports' to organize java import
;; ;; statements after importing via malabar or on save
(require-package 'jtags)
;; (autoload 'jtags-mode "jtags" "Toggle jtags mode." t)

(custom-set-variables
 '(jtags-extras-import-order-list
   ;; '("^static[\s]+"
   ;;   "-"
   ;;   "^io.vos\."
   ;;   "^proto\."
   ;;   "-"
   ;;   "^com\."
   ;;   "^io\."
   ;;   "^org\.(?!junit)"
   ;;   "^net\."
   ;;   "-"
   ;;   "^java\."
   ;;   "^javax\."
   ;;   "-"
   ;;   "^org\.junit\."))
   '("^static[\s]+"
     "-"
     "^io.vos\."
     "^proto\."
     "-"
     "^com\."
     "^io\."
     "^org\."
     "^net\."
     "-"
     "^java\."
     "^javax\."
     "-"
     "^org\.junit\."))
 ;; '(malabar-import-post-insert-function 'jtags-extras-organize-imports)
 )

(require-package 'javadoc-lookup)
(require 'javadoc-import)

;; Adds the hook only in java-mode. see:
;; http://stackoverflow.com/questions/6138029/how-to-add-a-hook-to-only-run-in-a-particular-mode

;; aliases defun `javadoc-import/javadoc-sort-imports' from
;; javadoc-lookup package to
;; `jtags-extras-organize-imports'. I'm using javadoc-lookup
;; for locating import artifacts, but jtags custom sort
;; order to organize imports. When calling
;; java-import/add-java-import it automatically calls
;; sort-java-imports. Using the import ordering from only
;; jtags keeps imports in the correct order.
(defalias 'javadoc-sort-imports 'jtags-extras-organize-imports)
(add-hook 'java-mode-hook
          (lambda ()
            ;; Sort imports before save
            (add-hook 'before-save-hook
                      'jtags-extras-organize-imports nil t)))

;; jtags-javadoc-root-alist : <M-f1> at point in jtags-mode
;; Alist of package patterns vs corresponding Javadoc root URLs.
;; Each element looks like (REGEXP . URL) where REGEXP is a regexp
;; that matches a group of imports, and URL is the Javadoc root URL
;; for that group of imports.  The Javadoc root URL is where the
;; "index.html" file resides.
;; (add-to-list 'jtags-javadoc-root-alist
;;              '(("^io.vertx\\." . "http://vertx.io/docs/apidocs/")
;;                ("^io.reactivex\\." . "http://reactivex.io/RxJava/2.x/javadoc/")))
;; ((("^java\\." . "https://docs.oracle.com/javase/8/docs/api")
;;   ("^javax\\." . "https://docs.oracle.com/javase/8/docs/api")))

;;; javadoc-lookup sources
;;; @see http://nullprogram.com/blog/2013/01/30/

;; (add-hook 'after-init-hook
;;           (lambda ()
;;             (javadoc-add-roots "/usr/share/javadoc/java"
;;                                ;; generated by ~/workspace/src/io.vos/build_docs.sh
;;                                "/home/erick/javadoc/io.vos")))

(add-hook 'after-init-hook
          (lambda ()
            (javadoc-add-roots "/home/erick/workspace/doc/javadoc/java")))

(javadoc-add-artifacts [com.google.guava guava "21.0"]
                       [junit junit 4.12])

(add-hook 'java-mode-hook
          (lambda ()
            (local-set-key (kbd "C-h j") (quote javadoc-lookup))
            (local-set-key (kbd "C-c C-i") (quote javadoc-add-import))))

;;; Fix indenting after wrapping after an annotation
(defun my-custom-java-mode-annoations-setup ()
  "Additional setup from `malabar-annotations-setup' for lining
  up statements following an annotation with the
  annotation. Rather than indenting."
  (c-prepend-offset 'annotation-var-cont 'c-no-indent-after-java-annotations))

                                        ; Use google-c-style for Java editing

(require-package 'google-c-style)
(defun my-setup-java-style ()
  "Sets the current buffers' java-style. Meant to be added to the
   `java-mode-hook'."
  (interactive)
  (google-make-newline-indent)
  (google-set-c-style)
  (setq fill-column 100)
  (setq tab-width 2)

  ;; https://www.gnu.org/software/emacs/manual/html_node/ccmode/c_002doffsets_002dalist.html
  ;;
  ;; C-c C-s -> c-show-syntactic-information, print syntactive
  ;; indentation information
  ;;
  ;; (describe-variable c-offsets-aliast) for a description of
  ;; syntactic elements. Run from a Java buffer to see the current
  ;; values
  ;;
  ;; Line-up functions:
  ;; https://www.gnu.org/software/emacs/manual/html_node/ccmode/Line_002dUp-Functions.html#Line_002dUp-Functions
  (c-set-offset 'arglist-cont-nonempty '++)
  ;; (c-set-offset 'statement-cont . (my-custom-statement-cont-indent))
  )

(defun my-java-mode-map ()
  (define-key java-mode-map "\C-cr" 'recompile))

(add-hook 'java-mode-hook 'jtags-mode)
(add-hook 'java-mode-hook 'subword-mode)
(add-hook 'java-mode-hook 'my-setup-java-style)
(add-hook 'java-mode-hook 'my-java-mode-map)

(provide 'init-java)
